Repository MagnusDot/MegaBot, pull requests merged in 2020-10, with the labels that each got.

#46 docs(website): update configuration website
  docusaurus/website/package-lock.json
  docusaurus/website/siteConfig.js
  docusaurus/website/static/img/esgi.jpg
  docusaurus/website/static/img/jason.png
Labels: documentation, hacktoberfest-accepted

#51 Dev/#43
  Dockerfile
Labels: enhancement, hacktoberfest-accepted

#52 fix: Adding error permission change
  Commands/React/DeleteReaction.ts
  Commands/React/React.ts
  bot.ts
Labels: bug

#55 Add Clear Features ( #53 )
  Commands/Clear.ts
  Commands/Help.ts
  README.md
  bot.ts
Labels: hacktoberfest-accepted
